version: '3.8'

services:
  mercury-kis-open-trading-api:
    build: .
    container_name: mercury-kis-open-trading-api
    image: mercury-kis-open-trading-api:latest
    ports:
      - "8001:8001"  # 포트 8001 사용
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - ENV=production
      - PYTHONPATH=/app
      - AWS_PROFILE=default
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./token:/app/token
      - ./config.py:/app/config.py
      - /home/ubuntu/.aws:/root/.aws:ro
    networks:
      - mercury_mercury-network

networks:
  mercury_mercury-network:
    external: true
